#!/usr/bin/env bash
# Regenerate docs/API_REFERENCE.md FROM THE EXTENSION.
#
# The function list is never hand-written: duckdb_functions() carries the
# signatures, descriptions and examples, and anofox-evolve derives its prompt
# vocabulary from exactly the same source. A hand-maintained list would drift
# from the binary, and a stale vocabulary is worse than none.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT="${1:-$ROOT/build/release/extension/anofox_optimize/anofox_optimize.duckdb_extension}"
DUCKDB="${DUCKDB:-$ROOT/build/release/duckdb}"
[ -f "$EXT" ] || { echo "extension not built: $EXT (run 'make release')" >&2; exit 1; }

{
  echo "# anofox-optimize API reference"
  echo
  echo "<!-- GENERATED by scripts/generate_api_reference.sh — do not edit by hand."
  echo "     Source of truth is duckdb_functions() in the built extension. -->"
  echo
  "$DUCKDB" -noheader -list -c "
    LOAD '$EXT';
    SELECT '## ' || function_name || chr(10) || chr(10) ||
           '\`' || function_name || '(' || COALESCE(parameter_types::VARCHAR,'') || ')\` -> \`'
                || COALESCE(return_type,'') || '\`' || chr(10) || chr(10) ||
           COALESCE(description,'_No description._') || chr(10) ||
           CASE WHEN examples IS NOT NULL AND examples::VARCHAR <> '[]'
                THEN chr(10) || 'Example: \`' || examples[1] || '\`' || chr(10) ELSE '' END
    FROM duckdb_functions()
    WHERE function_name LIKE 'anofox_optimize%' OR function_name LIKE 'opt_%'
    ORDER BY function_name;"
} > "$ROOT/docs/API_REFERENCE.md"
echo "wrote docs/API_REFERENCE.md"
